#!/usr/bin/env python3

# Angaza
"""
Uses Kconfig to modify configuration settings and generate an appropriate
configuration file used for building a Nexus project.
"""

import argparse
import platform
import sys

# Allow Kconfig tools to find the libraries required
sys.path.append('Kconfiglib')

if __name__ == "__main__":
    from Kconfiglib import guiconfig, kconfiglib, menuconfig

    if platform.system() == 'Windows':
        # For windows, default to guiconfig
        print("Detected Windows platform, using GUIConfig...")
        guiconfig._main()

    else:
        # Menuconfig works 'out of the box' on most *Nix distros:wq
        print("Detected *Nix platform, using menuconfig...")
        menuconfig._main()

    # Now generate headers
    kconf = kconfiglib.Kconfig('Kconfig', suppress_traceback=True)
    kconf.load_config()

    header_text = (
        u"/**-------------------------------------------\n"
        "DO NOT MODIFY, AUTOGENERATED CODE.\n"
        "TO CHANGE THESE VALUES, RUN\n"
        "`python conf_nexus.py` FROM THE PROJECT ROOT!\n"
        "---------------------------------------------*/\n\n"
    )
    kconf.write_autoconf("include/user_config.h", header_text)
