#!/usr/bin/expect -f

set timeout 2

proc expect_fail_timeout {expect_string} {
    expect {
        $expect_string {}
        timeout {send_user [subst {"\n Expect timed out waiting for" $expect_string}]; exit 1}
    }
}

spawn ./sample_nexus_keycode_program

expect_fail_timeout "Please enter the path"
send -- "test_nv_file.nv\r"

expect_fail_timeout "Please enter an integer serial ID"
send -- "123456789\r"

expect_fail_timeout "Please enter the 16-byte"
send -- "deadbeef1020304004030201feebdaed\r"

expect_fail_timeout "Credit remaining: 0 seconds"
expect_fail_timeout "Menu"
expect_fail_timeout "1. Enter Nexus Keycode"
send -- "1\r"

expect_fail_timeout "Please input a Full keycode"
send -- "*10029054295608#\r\r"

expect_fail_timeout "Keycode is valid."
expect_fail_timeout "Credit remaining: 86400"
send -- "\r"

expect_fail_timeout "Menu"
expect_fail_timeout "1. Enter Nexus Keycode"
send -- "1\r"

expect_fail_timeout "Please input a Full keycode"
send -- "*10029054295608#\r\r"

expect_fail_timeout "Keycode is valid; but, is either a duplicate or had no effect"
expect_fail_timeout "Credit remaining: 86400"
send -- "\r"

expect_fail_timeout "Menu"
expect_fail_timeout "1. Enter Nexus Keycode"
send -- "1\r"

expect_fail_timeout "Please input a Full keycode"
send -- "*47700886956615#\r\r"

expect_fail_timeout "Keycode is valid."
expect_fail_timeout "Credit remaining: 172800"
send -- "\r"

expect_fail_timeout "Menu"
expect_fail_timeout "1. Enter Nexus Keycode"
sleep 5

# Ensure that timekeeping decrements correctly
send -- "1\r"
expect_fail_timeout "Please input a Full keycode"
send -- "*47700886956615#\r\r"

expect_fail_timeout "Keycode is valid; but, is either a duplicate or had no effect"
expect_fail_timeout "Credit remaining: 172795"

# Close and reload, confirm data is loaded from the NV file correctly
close

spawn ./sample_nexus_keycode_program

expect "Please enter the path"
send -- "test_nv_file.nv\r"

expect_fail_timeout "Initializing Nexus library..."
expect_fail_timeout "Done"
expect_fail_timeout "Credit remaining: 172795 seconds"

close
exit
