/**-------------------------------------------
DO NOT MODIFY, AUTOGENERATED CODE.
TO CHANGE THESE VALUES, RUN
`python conf_nexus.py` FROM THE PROJECT ROOT!
---------------------------------------------*/

#define CONFIG_NEXUS_COMMON_ENABLED 1
#define CONFIG_NEXUS_CHANNEL_CORE_ENABLED 1
